apiVersion: v1
kind: Service
metadata:
  name: {{ include "Frontend.fullname" . }}
  labels:
    {{- include "Frontend.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5500
      nodePort: {{ .Values.service.nodePort | default "null" }}
  selector:
    app: {{ include "Frontend.name" . }}
