name: Push Docker Image to Docker Hub

on:
    create:
        tags:
          - '*'
    push:
        branches:
          - main
  
jobs:
    release:
        runs-on: ubuntu-latest
  
        steps:
        - uses: actions/checkout@v3
  
        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PW }}
  
        # - name: Build and Push Docker images
        #   run: |
        #       TAG_NAME=$(echo $GITHUB_REF | sed 's/refs\/tags\///') 
        #       docker buildx build --platform linux/arm64 -t ${{ secrets.DOCKER_USERNAME }}/myrepo:${TAG_NAME} . && docker push ${{ secrets.DOCKER_USERNAME }}/myrepo:${TAG_NAME}

        - name: Change config repo
          env:
              GITHUB_TOKEN: ${{ secrets.TOKEN }}
          run: |
              # TAG_NAME=$(echo $GITHUB_REF | sed 's/refs\/tags\///') 
              git clone https://ngodanghuy162:${GITHUB_TOKEN}}@github.com/ngodanghuy162/config-front.git
              pwd
              cd config-front && sed -i "s/tag: \*/tag: 0.5/" values.yaml
              # sed -i "s/tag: .*/tag: ${TAG_NAME}/" values.yaml
              git config user.name 'ngodanghuy162'
              git config user.email 'ngohuy658@gmail.com'
              git add values.yaml
              git commit -m 'Update image tag to ${TAG_NAME}' || true
              git push origin master
